function map_ifcheck {
	[ "$position" = "39" ] && finish="True"
	[ "$position2" = "39" ] && finish="True"
	[ "${orig_map:$position:1}" = "#" ] && position="$last"
	[ "${orig_map:$position2:1}" = "#" ] && position2="$last2"
	[ "${orig_map:$shootpos:1}" = "#" ] && endshoot="true"
	[ "${orig_map:$shootpos:1}" = "'" ] && orig_map="${orig_map:0:$shootpos}\`${orig_map:$(($shootpos+1)):$((200-$shootpos))}"
	[ "${orig_map:$position:1}" = "'" ] && position="$last"
	[ "${orig_map:$position2:1}" = "'" ] && position2="$last2"
	[ "$position" = "60" ] && position="179"
	[ "$position" = "140" ] && position="99"
	[ "$position" = "79" ] && position="7"
	[ "$position" = "159" ] && position="163"
	[ "$position2" = "60" ] && position2="179"
	[ "$position2" = "140" ] && position2="99"
	[ "$position2" = "79" ] && position2="7"
	[ "$position2" = "159" ] && position2="163"
	[ "$shootpos" = "60" ] && shootpos="179"
	[ "$shootpos" = "140" ] && shootpos="99"
	[ "$shootpos" = "79" ] && shootpos="7"
	[ "$shootpos" = "159" ] && shootpos="163"
}
