function map_ifcheck {
	[ "$shootpos" = "86" ] && endshoot="true"
	[ "$shootpos" = "81" ] && endshoot="true"
	[ "$shootpos" = "163" ] && endshoot="true"
	[ "$shootpos" = "170" ] && endshoot="true"
	[ "$shootpos" = "132" ] && endshoot="true"
	[ "$shootpos" = "93" ] && endshoot="true"
	[ "$shootpos" = "88" ] && endshoot="true"
	[ "$shootpos" = "133" ] && endshoot="true"
	[ "$shootpos" = "152" ] && endshoot="true"
	[ "$shootpos" = "158" ] && endshoot="true"
	[ "$shootpos" = "137" ] && endshoot="true"
	[ "$shootpos" = "198" ] && endshoot="true"
	[ "$shootpos" = "195" ] && endshoot="true"
	[ "$shootpos" = "192" ] && endshoot="true"
	[ "$shootpos" = "197" ] && endshoot="true"
	[ "$shootpos" = "138" ] && endshoot="true"
	[ "$shootpos" = "137" ] && endshoot="true"
	[ "$shootpos" = "98" ] && endshoot="true"
	[ "$shootpos" = "95" ] && endshoot="true"
	[ "$position" = "95" ] && finish="True"
	[ "$position2" = "95" ] && finish="True"
	[ "${orig_map:$position:1}" = "#" ] && position="$last"
	[ "${orig_map:$position2:1}" = "#" ] && position2="$last2"
	[ "${orig_map:$shootpos:1}" = "#" ] && endshoot="true"
}
